### ISSUE TITLE
[streamx-console, streamx-plugin] workspace storage compatibility for HDFS and LFS

### ISSUE THREAD

**Issue by Al-assad** [streamxhub/streamx#251]

**Comment by Al-assad** [comment]
this is the brief description of the implementation for unified file system operator, actually in process of coding.
![streamx-unifiled-fs-refactor](https://user-images.githubusercontent.com/22493821/126111702-6934ff2d-18ac-4649-ab79-ca6410385ecf.png)

**Comment by wolfboys** [comment]
> this is the brief description of the implementation for unified file system operator, actually in process of coding.

There is one area for improvement:

The current implementation is to identify which fsoperator to use according to the storagetype in the configuration.yml This method can be improved because this change is global. A better way is to automatically identify which FsOperator to use according to the deployment mode(yarn|k8s|local) of specific tasks
