### ISSUE TITLE
[Bug] When the ZK restarts, task monitoring is lost on the console

### ISSUE THREAD

**Issue by 1353297670** [streamxhub/streamx#266]
*请在提交你的 issue 前，请回答以下问题，这有助于社区快速定位问题，谢谢！ 🙏*

### Environment Description
* **StreamX Version**: 1.1.0
* **JVM version** (`java -version`):1.8

### Bug Description（Bug 描述）
When I restart the ZK cluster, although the task is still running on Yarn, but the status of the task in the console becomes LOST.

### Requirement or improvement
It is hoped that when the ZK restarts, the task status can be obtained again in the console

**Comment by Al-assad** [comment]
Hi @1353297670, It looks like this issue was cause by the yarn interface not actively refreshing when fetching Yarn RM web http address.
You can try modifying `HadoopUtils.getRMWebAppURL(false)` to  `HadoopUtils.getRMWebAppURL(true)` in [`ApplicationController#yarn()`]( https://github.com/streamxhub/streamx/blob/main/streamx-console/streamx-console-service/src/main/java/com/streamxhub/streamx/console/core/controller/ApplicationController.java#L156). If it works, maybe we can design a failure refresh mechanism on this interface, also welcome to submit related bug-fix pr.

**Comment by 1353297670** [comment]
Hi @AI-assad, Thanks for your advice, I will change it to true and try it.

**Comment by 1353297670** [comment]
Hi @AI-assad, When I change it to true and restart the yarn cluster , the task status is still lost

**Comment by wolfboys** [comment]
In the current deployment mode (flink on yarn),operations like yours are bound to go wrong,this is no longer a program can solve. keep yarn activity is the most basic guarantee
